export const DbCivilStatus = [
  "annulled",
  "divorced",
  "married",
  "widower",
  "single",
  "widow",
];

export const DbReligion = [
  "religion",
  "PPI",
  "Aglipayan",
  "ALLIANCE",
  "Atheists",
  "Banahaw",
  "Baptist",
  "Buddhist",
  "Dating Daan",
  "El Shaddai",
  "Episcopal",
  "Evangelical",
  "GWMC",
  "Hindu",
  "INC",
  "Indigeneous",
  "Islam",
  "JC",
  "Jehovah",
  "Judaism",
  "Latter",
  "Lutheran",
  "Mennonites",
  "Methodist",
  "Nazarene",
  "None",
  "Others",
  "PBMA",
  "Presbyterian",
  "Protestant",
  "CATHOLIC",
  "FOURSQUARE",
  "Seventh-Day",
  "UCCP",
  "Unitarian",
  "WCG",
  "WESLEYAN",
  "Born Again",
  "PRES",
  "IFI",
  "CHRISTIAN",
  "PENTECOSTAL",
  "CAMACOP",
  "Southern Baptist",
  "ALPHA AND OMEGA",
  "COC",
  "ECOFI",
  "MORMONS",
  "HOPE",
  "ZION",
  "IGLESIA SA DIOS ESPIRITU",
  "GPF",
  "LDS",
  "Church of God",
  "Bag-ong Herosalem",
  "Good News",
  "ANGLICAN",
  "CDCC",
  "full gospel",
  "espiritista",
  "iglesia rosa mistika fili",
  "UPC",
  "messiah assembly",
  "PICC",
  "JIL",
  "FAITH TRIBAL MINISTRY",
  "AOG",
  "YEMENE",
  "UNIVERSAL",
  "Lutheran Cath",
  "IGLESIAFILIPINA",
  "Sikh",
  "CHHEALER",
  "BUKYO",
  "FAITH TABERNACLE",
  "Orthodox",
  "JEWISH",
  "KINGDOM",
  "Moncadista",
];

export const DbNationality = [
  "nationality",
  "American",
  "Australian",
  "BELGIAN",
  "British",
  "BULGARIAN",
  "Canadian",
  "CHINESE",
  "Colombian",
  "COSTA",
  "Dutch",
  "Egyptian",
  "Fil-Am",
  "Fil-German",
  "Fil-Jap",
  "Filipino",
  "French",
  "German",
  "GREEK",
  "HONDURANS",
  "Indian",
  "Indonesian",
  "Irish",
  "Japanese",
  "KENYAN",
  "Korean",
  "LEBANESE",
  "Malaysian",
  "MEXICAN",
  "Myanmar",
  "Norwegian",
  "Panamian",
  "RUSSIAN",
  "SAUDI",
  "SINGAPOREAN",
  "SRI-LANKA 	 ",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanesse",
];

export const DbBrgyOfficialPositions = [
  "kagawad",
  "Secretary",
  "Treasurer",
  "Punong Barangay",
  "Day Care Worker",
  "Utility Worker",
  "Health Worker",
];
